version: '3.7'
services:
  db:
    image: postgres:13.8-alpine3.16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
